export enum Color {
  PrimaryColor,
  ButtonShadowColor,
  TextColor,
  TextSecondaryColor,
  ButtonTextColor,
  SecondaryColor1,
  SecondaryColor2,
  RedColor,
  ErrorColor,
  SuccessColor,
  WarningColor,
  CarouselCardShadowColor,
  CarouselCardHoveredShadowColor,
}
